name: RIABandwidthSaver
version: '${project.version}'
main: com.ghostchu.plugins.riabandwidthsaver.RIABandwidthSaver
api-version: '1.20'
depend:
  - CMI
  - ProtocolLib
commands:
  riabandwidthsaver:
    usage: /riabandwidthsaver